"""
Terraform tfvars file generator for the AWS Security Baseline Deployment Wizard.

This module provides functions for generating terraform.tfvars files from
wizard configuration, with proper HCL syntax and file overwrite handling.

**Validates: Requirements 7.1, 7.2, 7.3, 7.4**
"""

from pathlib import Path
from typing import Optional

from rich.console import Console
from rich.prompt import Confirm

from wizard.models import AVAILABLE_MODULES, WizardConfig


def generate_tfvars_content(config: WizardConfig) -> str:
    """Generate terraform.tfvars content from configuration.

    Creates valid HCL syntax for all settings including:
    - Environment and region configuration
    - Module enable flags
    - Resource tags

    Args:
        config: The WizardConfig containing all user selections.

    Returns:
        String containing the terraform.tfvars content in HCL format.

    **Validates: Requirements 7.1, 7.2, 7.3**
    """
    lines = []

    # Header comment
    lines.append("# AWS Security Baseline Configuration")
    lines.append("# Generated by the Deployment Wizard")
    lines.append("")

    # Environment Configuration
    lines.append("# Environment Configuration")
    lines.append(f'environment = "{config.environment}"')
    lines.append(f'aws_region  = "{config.region}"')
    lines.append("")

    # Module Enable Flags
    lines.append("# Module Enable Flags")
    for module in AVAILABLE_MODULES:
        enabled = config.modules.get(module.name, False)
        enabled_str = "true" if enabled else "false"
        lines.append(f"{module.var_name} = {enabled_str}")
    lines.append("")

    # Common Tags
    lines.append("# Common Tags")
    lines.append("common_tags = {")
    for key, value in config.tags.items():
        # Escape any quotes in the value
        escaped_value = value.replace('"', '\\"')
        lines.append(f'  {key} = "{escaped_value}"')
    lines.append("}")

    return "\n".join(lines)


def parse_tfvars_content(content: str) -> WizardConfig:
    """Parse terraform.tfvars content back into a WizardConfig.

    This function is the inverse of generate_tfvars_content and is used
    for round-trip testing to verify that generated content can be
    parsed back to equivalent configuration.

    Args:
        content: The terraform.tfvars content string.

    Returns:
        WizardConfig parsed from the content.

    **Validates: Requirements 7.1, 7.2, 7.3**
    """
    config = WizardConfig()

    # Initialize modules dict
    config.modules = {}
    config.tags = {}

    lines = content.split("\n")
    in_tags_block = False

    for line in lines:
        line = line.strip()

        # Skip comments and empty lines
        if not line or line.startswith("#"):
            continue

        # Handle tags block
        if line == "common_tags = {":
            in_tags_block = True
            continue

        if in_tags_block:
            if line == "}":
                in_tags_block = False
                continue

            # Parse tag line: key = "value"
            if "=" in line:
                parts = line.split("=", 1)
                key = parts[0].strip()
                value_part = parts[1].strip()
                # Remove surrounding quotes
                if value_part.startswith('"') and value_part.endswith('"'):
                    value = value_part[1:-1]
                else:
                    value = value_part
                # Unescape quotes
                value = value.replace('\\"', '"')
                config.tags[key] = value
            continue

        # Parse regular assignments
        if "=" in line:
            parts = line.split("=", 1)
            key = parts[0].strip()
            value = parts[1].strip()

            if key == "environment":
                config.environment = value.strip('"')
            elif key == "aws_region":
                config.region = value.strip('"')
            elif key.startswith("enable_"):
                # Module enable flag
                module_name = key.replace("enable_", "")
                config.modules[module_name] = value == "true"

    return config


def generate_tfvars(
    config: WizardConfig,
    output_path: str = "terraform.tfvars",
    console: Optional[Console] = None,
    force_overwrite: bool = False,
) -> bool:
    """Generate terraform.tfvars file from configuration.

    Creates a terraform.tfvars file with all settings from the wizard
    configuration. Handles file overwrite confirmation if the file
    already exists.

    Args:
        config: The WizardConfig containing all user selections.
        output_path: Path to the output file (default: terraform.tfvars).
        console: Optional Rich Console instance. If None, creates a new one.
        force_overwrite: If True, overwrite without confirmation.

    Returns:
        True if file was successfully written, False otherwise.

    **Validates: Requirements 7.1, 7.2, 7.3, 7.4**
    """
    if console is None:
        console = Console()

    # Check if file exists
    path = Path(output_path)
    if path.exists() and not force_overwrite:
        console.print(f"\n[yellow]⚠ File '{output_path}' already exists.[/yellow]")
        overwrite = Confirm.ask("Overwrite existing file?", default=False)
        if not overwrite:
            console.print("[dim]File generation cancelled.[/dim]")
            return False

    # Generate content
    content = generate_tfvars_content(config)

    try:
        # Write file
        path.write_text(content)
        console.print(f"\n[green]✓ Generated {output_path}[/green]")
        return True
    except OSError as e:
        console.print(f"\n[red]✗ Failed to write {output_path}: {e}[/red]")
        console.print("[dim]Check file permissions and try again.[/dim]")
        return False
